# Build applikasjonen
# For å bygge applikasjonen trenger vi node-image.

# For å unngå å rote seg bort i ukjente mapper og filer ønsker vi å sette en WorkingDirectory.

# Vi må kopiere package.json til Docker

# Vi installerer dependencies.

# Vi kopierer resten av filene våre over til Docker.

# Vi utfører bygging av frontend-prosjektet.


# Bygg en Nginx-server til å "hoste" applikasjonen.
# For dette trenger vi nginx-image.

# I Nginx sin default configuration ser den etter frontendfiler i /usr/share/nginx/html. 
# Vi kan endre dette med en nginx.conf-fil eller legge filer rett i mappen
# Derfor setter vi WORKDIR til /usr/share/nginx/html

# Etter å ha satt WORKDIR ønsker vi å slette default "nginx-static-resource"-filene som ligger der.  

# Vi ønsker å hente innholdet fra vår tidligere build-versjon av applikasjonen og overføre det til vår posisjon

# Vi må spesifisere instruksjonen som applikasjonen i containeren skal kjøre.
